version: '3.8'

services:
  app:
    container_name: shelf_app
    build:
      context: .
      target: development # Build the specified stage as defined inside the Dockerfile
    image: shelf:1.0.0
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - db
    networks:
      - shelf
  db:
    container_name: "${DB_HOST}"
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:${DB_PORT}"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - shelf
    healthcheck:
      test: ["CMD","mysqladmin","ping","-p","${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  shelf:
    driver: bridge

volumes:
  mysql:
    driver: local

